config/routes.rb
Rails.application.routes.draw do

  root 'prototypes#index'

  devise_for :users

  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:index, :show]

  namespace :prototypes do
    resources :popular, only: :index
  end

  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  validates :title, :catchcopy, :concept, presence: true
  belongs_to :user
  has_one :main_image, -> { where(role: PrototypeImage.roles[:main]) }, class_name: "PrototypeImage"
  has_many :prototype_images, dependent: :delete_all
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :delete_all
  accepts_nested_attributes_for :prototype_images, reject_if: :reject_sub_images, allow_destroy: true

  acts_as_taggable
  paginates_per 5

  def like_user(user)
   likes.find_by(user_id: user.id)
  end

  def reject_sub_images(attributed)
    attributed['image'].blank?
  end
end

app/models/prototype_image.rb
class PrototypeImage < ActiveRecord::Base
  validates :image, :role, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :prototype
  enum role: %i(main sub)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, :nickname, :member, :profile, :works, presence: true
  mount_uploader :avatar, AvatarUploader
  has_many :prototypes
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  add_flash_types :success, :info, :warning, :danger
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:nickname, :member, :profile, :works)
    devise_parameter_sanitizer.for(:sign_in).push(:nickname, :member, :profile, :works)
    devise_parameter_sanitizer.for(:account_update).push(:nickname, :member, :profile, :works)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_product, only: :create

  def create
    @prototype.comments.create(comment_params)
    @comments = @prototype.comments
  end

  private

  def set_product
    @prototype = Prototype.find(params[:prototype_id])
  end

  def comment_params
    params.require(:comment).permit(:user_id, :content)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @prototype = Prototype.find(params[:prototype_id])
    @prototype.likes.create(user_id: current_user.id)
  end

  def destroy
    @like = current_user.likes.find_by(prototype_id: params[:id])
    @like.destroy
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/popular_controller.rb
class PopularController < ApplicationController

  def index
    @prototypes = Prototype.includes(:user).order(likes_count: :DESC)
    render 'prototypes/index'
  end

end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < PrototypesController

  def index
    @prototypes = Prototype.includes(:user).order(likes_count: :DESC)
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!
  before_action :define_prototype, except: [:index, :new, :create]

  def index
    @prototypes = Prototype.order(created_at: :DESC).page(params[:page])
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user, :prototype)
  end

  def new
    @prototype = Prototype.new
    @prototype.prototype_images.build
  end

  def create
    @prototype = Prototype.new(prototype_params)

    if @prototype.save
      redirect_to root_path, notice: 'Saved successfully'
    else
      render :new, alert: 'Failed to Save'
    end
  end

  def update
    if @prototype.update(prototype_params)
      redirect_to root_path, notice: 'Updated successfully'
    else
      render :edit
    end
  end

  def destroy
    if @prototype.user_id == current_user.id
      @prototype.destroy
      redirect_to root_path, notice: 'Deleted successfully'
    end
  end

  private

  def prototype_params
    params.require(:prototype).permit(:title, :catchcopy, :concept, :user_id, prototype_images_attributes: [:id, :image, :role, :prototype_id]).merge(tag_list: params[:prototype][:tag_list])
  end

  def define_prototype
    @prototype = Prototype.find(params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @prototypes = Prototype.tagged_with(@tag).includes(:user).order(created_at: :DESC)
    render "prototypes/index"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]
  before_action :user, only: [:show, :edit, :update]

  def show
    @user = User.find(params[:id])
    @prototypes = @user.prototypes.order(created_at: :DESC)
  end

  def edit
  end

  def update
    if current_user.update(update_params)
      redirect_to root_path, notice: "Successfully update user."
    else
      render :edit
    end
  end

  private
  def user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:user).permit(:email ,:nickname, :member, :profile, :works, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def post_main_image_helper
    @prototype.main_image.present? ? @prototype.main_image : ""
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/popular_helper.rb
module PopularHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to image_tag(comment.user.avatar, class: "media-object", style: "width: 64px; height: 64px;"), user_path(@prototype.user)
  .media-body
    %h4#top-aligned-media.meadia-heading
      = comment.user.nickname
      = link_to "#top-aligned-media", class: 'anchorjs-link' do
        %span.anchorjs-icon
      %p= comment.content

app/views/comments/create.js.haml
$("#comment_text").val("");
$("#js-comments-count").text("(#{ @comments.count })");
$("#js-comments").html("#{ j(render partial: 'comment', collection: @comments) }");

app/views/layouts/_error.html.haml
- if danger.errors.any?
  %div{ class: "alert alert-danger" }
    %a{ href: "#", "data-dismiss": "alert", class: "close" }
    %ul
      - danger.errors.full_messages.each do |message|
        %li
          = message

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav.navbar-right
        - unless user_signed_in?
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get started', new_user_session_path
          //login
        - else
          %li.dropdown
            %a.dropdown-toggle{ aria: { expanded: true }, data: { toggle: :dropdown }, role: "button" }
              = current_user.nickname
              %span.caret
              %ul.dropdown-menu{ role: "menu" }
                %li
                  = link_to 'Profile Edit', edit_user_path(current_user)
                %li
                  = link_to 'Logout', destroy_user_session_path, method: :delete
                %li
                  %a{:href => "/users/#{current_user.id}"} My page
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path

app/views/layouts/_message.html.haml
- flash.each do |key, value|
  - key == "info" ? key = "notice" : key = "alert"
  = content_tag :div, value, class: "alert alert-#{key}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = render "layouts/message"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if @prototype.like_user(current_user)
    = button_to prototype_like_path(current_user, @prototype), method: :delete, class: "btn btn-default", id: "js-like-button", remote: true do
      = image_tag("icon_heart_red.svg")
      Like
      = @prototype.likes_count
  - else
    = button_to prototype_likes_path(@prototype), method: :post, class: "btn btn-default", id: "js-like-button", remote: true do
      = image_tag("icon_heart.svg")
      Like
      = @prototype.likes_count
- else
  = image_tag("icon_heart_red.svg")
  Like
  = @prototype.likes_count

app/views/likes/create.js.haml
$("#js-like-buttons").html("#{j(render 'likes/like')}");

app/views/likes/destroy.js.haml
$("#js-like-buttons").html("#{j(render 'likes/like')}");

app/views/prototypes/_edit_form.html.haml
%ul.proto-sub-list.list-group
  = f.fields_for :prototype_images, (@prototype.prototype_images.sub) do |sub_image|
    %li.list-group-item.col-md-12.appear_form
      .image-upload.js-preview
        = sub_image.file_field :image
        = sub_image.hidden_field :role, value: :sub
%li.list-group-item.col-md-12
  .image-upload-plus
    %span +

app/views/prototypes/_form.html.haml
= form_for @prototype, html: {class: 'container proto-new'} do |f|
  = render "layouts/error", danger: @prototype
  = f.hidden_field :user_id, value: current_user.id
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = f.text_field :title, placeholder: "Title", class: "proto-new-title", required: true
    .row
      .col-md-12
        .cover-image-upload.js-preview
          = f.fields_for :prototype_images, post_main_image_helper do |main_image|
            = main_image.file_field :image
            = main_image.hidden_field :role, value: :main
      .col-md-12
        = render "#{action}_form", f: f
    .row.proto-description
      .col-md-12
        = f.text_field :catchcopy, placeholder: "Catch Copy", required: true
      .col-md-12
        = f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept", required: true
      .col-md-12
        %h4 Tag List
        .row
          - 3.times do |num|
            .col-md-12
              = text_field_tag "prototype[tag_list][]", "#{@prototype.tag_list[num]}", placeholder: "Tag #{num+1}"
    .row.text-center.proto-btn
      = f.submit "Publish", class: "button btn btn-lg btn-primary btn-block"

app/views/prototypes/_new_form.html.haml
%ul.proto-sub-list.list-group
  - 2.times do
    = f.fields_for :prototype_images do |sub_image|
      %li.list-group-item.col-md-4.appear_form
        .image-upload.js-preview
          = sub_image.file_field :image
          = sub_image.hidden_field :role, value: :sub
  %li.list-group-item.col-md-4
    .image-upload-plus
      %span +

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    - if user_signed_in? && current_user.id == prototype.user_id
      .dropdown.drop_menu_location
        %button.btn.btn-default{ id: "dropdownMenu", type: "button", data: { toggle: "dropdown" } } action
        %ul.dropdown-menu{ area: { labelledby: "dropdownMenu1" } }
          %li
            = link_to "Delete", prototype_path(prototype), method: :delete, data: { confirm: "Are you sure you want to permanently delete ?" }
          %li
            = link_to "Edit",  edit_prototype_path(prototype)
    = link_to image_tag(prototype.main_image), prototype_path(prototype.id)
    .caption
      %h3
      = prototype.title
      .proto-metaproto
        .proto-user
          = link_to "by #{prototype.user.nickname}", user_path(prototype.user)
        .proto-posted
          = prototype.created_at.strftime('%m/%d')
      %ul.proto-tag-list.list-inline
      - prototype.tags.each do |tag|
        %li
          = link_to tag.name, tag_path(tag), class: "btn btn-default"

app/views/prototypes/edit.html.haml
= render "form", action: :edit

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{ class: "#{ 'active' if current_page?(prototypes_popular_index_path) }"}
          = link_to "Popular PROTO", prototypes_popular_index_path
        %li{ class: "#{ 'active' if current_page?(root_path) }"}
          = link_to "Newest PROTO", root_path
      =button_tag "View Tags", type: "button", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes

.text-center
  %ul.pagination
    %li.disabled
      = paginate(@prototypes)

app/views/prototypes/new.html.haml
= render "form", action: :new

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag(@prototype.user.avatar, size: "64x64", class: "media-object"), user_path(@prototype.user)
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to "by#{@prototype.user.nickname}", user_path(@prototype.user)
            %span.degree= @prototype.user.profile
    .col-md-6.text-right
      #js-like-buttons
        = render "likes/like"
  .row
    .col-md-9
      = image_tag @prototype.prototype_images.main.first.image, class: 'img-responsive'
    .col-md-3
      %ul.proto-sub-list.list-group
      - @prototype.prototype_images.sub.each do |sub_image|
        %li.list-group-item
          = image_tag sub_image.image, class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p= @prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p= @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
      - @prototype.tags.each do |tag|
        %li
          = link_to tag.name, tag_path(tag), class: "btn btn-default"
    .col-md-8
      #js-comments
        = render partial: "comments/comment", collection: @comments
      - if user_signed_in?
        = form_for [@prototype, @comment], remote: true do |f|
          = f.hidden_field :user_id, value: current_user.id
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :content, require: true, rows: "3", placeholder: "Your comments", id: "comment_text", class: "form-control"
            .form-group.col-md-2
              = f.submit "COMMENT", class: "button btn btn-primary"

app/views/tags/index.html.haml
.container
  .row
    .tag-list
      %h2 Tags list
    - @tags.each do |tag|
      %ul
        .col-md-4
          =link_to tag.name, tag_path(tag), class: "btn btn-default btn-tag"

app/views/users/edit.html.haml
= render 'layouts/error', danger: current_user
= form_for(current_user, html: {class: "container user-new"}) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %h2 Edit Profile
        .user-name_image.row
          .user-name.col-md-10
            = f.text_field :nickname, placeholder: "Username"
          .user-image.col-md-2.js-preview
            = f.button "Change image", class: "btn btn-primary"
            = f.file_field :avatar
        = f.text_field :email, placeholder: "E-Mail", class: "user-email"
        = f.password_field :password, placeholder: "Password", class: "user-password"
      .col-md-12
        %h4 Member of
        .user-user-member.row
          .user-name.col-md-12
            = f.text_field :member, placeholder: "Member"
        %h4 Profile
        .user-user-profile.row
          .user-name.col-md-12
            = f.text_area :profile, cols: "30", rows: "4", placeholder: "Profile"
        %h4 Works
        .user-name_image.row
          .user-name.col-md-12
            = f.text_area :works, cols: "30", rows: "4", placeholder: "Works"
    .row.text-center.user-btn
      = f.submit "Save", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar, alt: "64x64", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.nickname
          %span.label.label-default.project-number
            = @user.prototypes.count
            %i Projects
        .proto-user
          %span.degree
          = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p
            = @user.profile
          .col-md-6
            %h4 Works
            %p
            = @user.works
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  %ul.pagination
    %li.disabled